version: '2'
services:
  db:
    container_name: todo-app-db
    build:
      context: ./db/pg
  app:
    build: .
    container_name: todo-app
    environment:
      PGHOST: db
      PGPORT: 5432
      PGDATABASE: docker-demo-app
      PGUSER: ${PGUSER}
      PGPASSWORD: ${PGPASSWORD}
    ports:
      - "9000:9000"
    depends_on:
      - db
